name: Update Metadata [Manual]

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: PLaywright Setup
        run: bunx playwright install --with-deps chromium

      - name: Generate API
        run: bun run cli generate $GOOGLE_API_KEY
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Parse API
        run: bun run cli parse

      - name: Stage, commit and push files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: 'fontsource-bot'
          commit_user_email: '83556432+fontsource-bot@users.noreply.github.com'
          commit_author: 'fontsource-bot <83556432+fontsource-bot@users.noreply.github.com>'
          commit_message: 'chore(build): update API [Manual]'
        continue-on-error: true
